services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    command: npm run start
    env_file:
      - ./.env
    volumes:
      - .:/usr/src
  mongo:
    image: mongo